"""Add activity table

Revision ID: 25a248d8389b
Revises: 98c5da951bfb
Create Date: 2026-04-03 14:37:34.806257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25a248d8389b"
down_revision: Union[str, Sequence[str], None] = "98c5da951bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "COURSE_CREATED",
                "STUDENT_ADDED",
                "STUDENT_REMOVED",
                "STUDENTS_IMPORTED",
                name="activitytype",
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    op.execute("DROP TYPE IF EXISTS activitytype")
    # ### end Alembic commands ###
