"""remove_due_date_from_courses

Revision ID: 4b205f997e1c
Revises: e243a10e5472
Create Date: 2026-04-06 13:23:05.861629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b205f997e1c"
down_revision: Union[str, Sequence[str], None] = "e243a10e5472"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "due_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("due_date", sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
