"""Add activity table

Revision ID: e3e6bc01b8e0
Revises: 98c5da951bfb
Create Date: 2026-04-03 14:33:05.728532

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e3e6bc01b8e0"
down_revision: Union[str, Sequence[str], None] = "98c5da951bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
