import enum


class ActivityType(str, enum.Enum):
    COURSE_CREATED = "COURSE_CREATED"
    STUDENT_ADDED = "STUDENT_ADDED"
    STUDENT_REMOVED = "STUDENT_REMOVED"
    STUDENTS_IMPORTED = "STUDENTS_IMPORTED"
